---
version: '2'
services:

# Other systems
  mysql:
  #   # *-----------------------------*
  #   # To connect to the DB:
  #   #   docker-compose exec mysql bash -c 'mysql -u root -p$MYSQL_ROOT_PASSWORD'
  #   # *-----------------------------*
    image: mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tk_pazin
      - MYSQL_USER=connect_user
      - MYSQL_PASSWORD=asgard
      - TZ=Europe/Zagreb
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+02:00']
    volumes:
      - db-leach:/var/lib/mysql

volumes:
    db-leach: {}
